services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: locadora-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Str0ngP@ssw0rd!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: locadora-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # Emulador local do Azure Blob Storage (Azurite)
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: locadora-azurite
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000 -l /data"
    ports:
      - "10000:10000"
    volumes:
      - azurite-data:/data

  # API REST (.NET 10)
  api:
    build:
      context: ./btg-locadora-api
      dockerfile: Dockerfile
    container_name: locadora-api
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started
      azurite:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__SqlServerDB: "Server=sqlserver,1433;Database=DB_LOCADORA;User Id=sa;Password=Str0ngP@ssw0rd!;MultipleActiveResultSets=true;TrustServerCertificate=True;Encrypt=False"
      ConnectionStrings__Redis: "redis:6379"
      ConnectionStrings__BlobStorage: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
      BlobStorage__PublicBaseUrl: "http://127.0.0.1:10000/devstoreaccount1"
    ports:
      - "8080:8080"

  # Front-end (.NET 10)
  #web:
  #  build:
  #    context: ./btg-locadora-web
  #    dockerfile: Dockerfile
  #  container_name: locadora-web
  #  depends_on:
  #    api:
  #      condition: service_started
  #  environment:
  #    ASPNETCORE_ENVIRONMENT: "Development"
  #    ASPNETCORE_URLS: "http://+:8080"
  #    ApiBaseUrl: "http://api:8080/"
  #  ports:
  #    - "8081:8080"

volumes:
  sqlserver-data:
  redis-data:
  azurite-data:
